name: release
on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    release:
        environment: release
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 21

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    cache-read-only: false

            -   name: Change wrapper permissions
                run: chmod +x ./gradlew

            -   name: Publish to CurseForge, Modrinth
                run: ./gradlew build publishMods
                env:
                    CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
                    MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

            -   name: Upload built JARs
                uses: actions/upload-artifact@v4
                with:
                    name: skin-restorer-artifacts
                    path: ./*/build/libs/*.jar
