name: release
on: [ workflow_dispatch ]

jobs:
    release:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 21

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    cache-read-only: false

            -   name: Change wrapper permissions
                run: chmod +x ./gradlew

            -   name: Publish to CurseForge, Modrinth
                run: ./gradlew build publishMods
                env:
                    CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
                    MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

            -   name: Publish to GitHub
                uses: softprops/action-gh-release@v2
                with:
                    body_path: CHANGELOG_LATEST.md
                    files: |
                        fabric/build/libs/*.jar
                        forge/build/libs/*.jar
                        neoforge/build/libs/*.jar
